name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN permissions are limited to the repository that contains your workflow.
          # If you need to push the homebrew tap to another repository,
          # you must therefore create a custom Personal Access Token with repo permissions at https://github.com/settings/tokens
          # and add it as a secret in the repository.
          # If you create a secret named GH_PAT and uncomment the following line
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}